# Generated by Django 3.2.7 on 2021-09-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Owl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ioc_sequence", models.IntegerField()),
                ("common_name", models.CharField(max_length=64)),
                ("binomial_name", models.CharField(max_length=64)),
            ],
        ),
    ]
